### ISSUE TITLE
不支持半透明吗?

### ISSUE THREAD

**Issue by DLTech21** [MagicMashRoom/SuperShadow#2]
.setBaseShadowColor(Color.parseColor("#593B4A74"))?? 这样没有效果

**Comment by MagicMashRoom** [comment]
你可以使用setColors
public void setColors(int[] colors) {
        if (colors != null)
            this.colors = colors;
    }

传入一个你想要的渐变的颜色数组
比如说 你可以 int[] colors = new int[3]
colors[0] = Color.parseColor("#593B4A74");
colors[1] = Color.parseColor("#293B4A74");
colors[2] = Color.parseColor("#003B4A74");
